### ISSUE TITLE
I can't get it to run

### ISSUE THREAD

**Issue by vinniec** [JoBase/JoBase#4]
first of all I am happy to open the first issues 🥇

Yesterday while browsing I had come across your library but had not had time to try it, today I wanted to do so (but I had forgotten the name, I had even written a script to search through all the pypi packages, however I did not remember enough info as search keys, I finally got lucky and found it [here](https://wiki.python.org/moin/PythonGameLibraries) ).

Today I tried it and unfortunately it seems that the version of my opengl is not enough:
```
python -m JoBase.examples.physics
Welcome to JoBase
WGL: The driver does not appear to support OpenGL
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
OSError: failed to create window
```
in the past few days I also tried pyglet and had the same problem (only that being pyglet an older library, they pointed me to an older version and it worked).

However, I didn't give up and since your library should also work in the browser I wanted to try the examples, however I got this error: "OffscreenCanvas not available in your browser."
[I checked](https://caniuse.com/offscreencanvas) and my version of firefox (117) should work.
Then I tried chrome as well and that didn't work either, even though it also had support (118, latest version).

So I tried it on my phones, and after several trials, on a chrome of a phone it worked.
I was then able to try all three example games and the short tutorial.
The games went relatively well, "Blue Hue" the slowest, however the execution leaves a positive impression.

Honestly, I have never produced a game and only intended to display something as a technical proof of an idea, so I don't have any qualms about your library, instead I wish you to develop it well because it seems to me that it has a lot of potential.

I saw that there's also image magnification in the browser (or maybe it's the browser's own magnification?!?), however you could see the scaling, do you happen to think you'll support vector images as well?

if the problem with the OffScreenCanvas is surmountable without leaving dead and (perhaps) the browser could mitigate the need for an updated opengl, perhaps providing an online editor like the one in your tutorial could allow JoBase to be used even with an older pc.

**Comment by Grey41** [comment]
Congrats on raising the first issue!

You might be able to fix the OpenGL error if you update your graphics driver or reinstall OpenGL manually.

Thanks for your feedback on the browser version, it's a shame it didn't work for you. The upcoming version of JoBase doesn't use `OffscreenCanvas` anymore and the performance is a little better. I'll try to incorporate an online editor as well.

Overall, JoBase has limited performance in the browser; you'll get better results on your PC. You might get some useful ideas for fixing the problem if you search **GLFW Error 65542**.

Thanks again for the suggestions.

**Comment by vinniec** [comment]
Ok, thanks for the reply, I meant to answer you earlier but I was wrestling with the deadline for github's mandatory 2FA activation (I looked into it just enough and it seems like another industry gimmick to make things more unstable instead of more secure).

As for updating the drivers unfortunately it is something I cannot do at this time, the problem that on this pc right now windows 11 is installed and I cannot update the drivers (another gimmick).
And installing only opengl outside of drivers I don't know if it's feasible, the only alternative I found is to install mesa3d which however doesn't provide official binaries for windows, I found an unofficial distribution however trying a per-apps installation didn't work and I don't feel like breaking the whole system :D

I am usually a user of linux-based systems however I find myself with this pc that I have yet to "upgrade".

However, I gladly wait for the new version of JoBase to see if it works in my browsers.
The feature is very interesting because I think in this way we get as close as possible to writing an application once and running it on any platform, on the one hand using an interpreted language like python and directly opengl without other dependencies, on the other hand if it doesn't work there is always the browser.

As for the "GLFW Error 65542", I quickly tried replacing the "opengl32.dll" as recommended on one site but only got an error change :D
Forgive me, I don't really know how it works, I don't know if JoBase really only needs this single "opengl32.dll" file to work properly, but if so, wouldn't it be possible to provide the ability to specify a path to use a standalone version of it?
It reminds me so much in the days of quake when the game wouldn't work unless opengl was installed, good old days :P

**Comment by Grey41** [comment]
Hi @vinniec, it's been a while. The last few versions of JoBase have better support in browsers. I'd be interested to know if the [games](https://jobase.org/games) and [demos](https://jobase.org/demos) work in your version of Firefox.
